definitions:
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Unauthorized
          schema:
            type: string
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with username and password
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
      summary: Register a new user
      tags:
      - auth
swagger: "2.0"
